services:
  - type: web
    name: hrms-lite-backend
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: hrms_lite
